trigger:
- main

pool:
  vmImage: ubuntu-latest
  

stages:
- stage:
  jobs::
    - job:
      steps:
        - task: trivy@1
          inputs:
            path: .
            
        - task: trivy@1
          inputs:
          image: ubuntu