trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage:
  jobs:
   - job:
     steps:
       - task: Bash@3
         inputs:
           targetType: inline
           script: |
             docker login -u caesar269 -p Udai@1248
           
       - task: trivy@1
         inputs:
           version: 'latest'
           loginDockerConfig: true
           image: 'caesar269/nginx:true'