trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage:
  jobs:
   - job:
     steps:
     - task: AWSCLI@1
       inputs:
         awsCredentials: 'AWS'
         regionName: 'ap-south-1'
         awsCommand: 'aws --version'
         awsSubCommand: 'aws --version'