trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage:
  jobs:
   - job:
     steps:
     - task: Bash@3
       inputs:
         filePath: 'trivy.sh'
     - task: Bash@3
       inputs:
         targetType: 'inline'
         script: |
           docker pull caesar269/nginx:green
           trivy image caesar269/nginx:green