trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage:
  jobs:
   - job:
     steps:
     - task: trivy@1
       inputs:
        version: 'latest'
        loginDockerConfig: true
        image: 'nginx'