trigger:
- main

pool:
  vmImage: ubuntu-latest
  

stages:
- stage:
  jobs:
   - job:
     steps:
       - task: trivy@1
         inputs:
           version: 'latest'
           docker: false
           loginDockerConfig: true
           image: 'caesar269/nginx:red'