trigger:
- main

pool: tsar

stages:
- stage:
  jobs:
   - job:
     steps:
       - task: Bash@3
         inputs:
           targetType: inline
           script: |
             trivy image caesar269/nginx:red > nginx-red.json
