trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage:
  jobs:
   - job:
     steps:
     - task: Bash@3
       inputs:
         targetType: 'inline'
         script: |
           'wget https://github.com/aquasecurity/trivy/releases/download/v0.48.0/trivy_0.48.0_Linux-64bit.deb'
           'sudo dpkg -i trivy_0.48.0_Linux-64bit.deb'
