trigger:
  - main

pool:
  vmImage: ubuntu-latest
  

stages:
  - stage:
    jobs:
      - job:
        steps:
            - task: Bash@3
              inputs:
                targetType: filePath
                filePath: ./trivy.sh
            
            - task: Bash@3
              inputs:
                targetType: inline
                script: trivy image nginx