# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(977812bc-0cfb-4c57-8912-a7804ccf8fba)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create \
      --name AZ \
      --location eastus
      
      az network nsg create \
      --resource-group AZ \
      --name AZ-NSG
      
      az network nsg rule create \
      --resource-group AZ \
      --nsg-name AZ-NSG --name AZ_Nsg_Rule --priority 100 \
      --source-address-prefixes '*' --source-port-ranges '*' \
      --destination-address-prefixes '*' --destination-port-ranges '*' \
      --access Allow --protocol Tcp --description "Allowing ALL"
      
      for i in `seq 1  `; do
         az vm create \
           --resource-group AZ \
           --name Master$i \
           --size Standard_B1s  \
           --storage-sku StandardSSD_LRS \
           --os-disk-size-gb 32 \
           --vnet-name Vnet \
           --subnet Subnet \
           --nsg AZ-Nsg \
           --image Ubuntu2204 \
           --admin-username master \
           --admin-password "india@123456"
      done
      
      for i in `seq 1  `; do
         az vm create \
           --resource-group AZ \
           --name Node$i \
           --size Standard_B1s  \
           --storage-sku StandardSSD_LRS \
           --os-disk-size-gb 32 \
           --vnet-name Vnet \
           --subnet Subnet \
           --nsg AZ-Nsg \
           --image Ubuntu2204 \
           --admin-username node \
           --admin-password "india@123456"
      done
