trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage:
  jobs:
   - job:
     steps:
     - task: Bash@3
       inputs:
         filePath: 'trivy.sh'
     - task: Bash@3
       inputs:
         targetType: 'inline'
         script: |
           docker pull caesar269/nginx:green
           trivy image -f json -o results.json caesar269/nginx:green
     - task: DownloadBuildArtifacts@1
       inputs:
          buildType: 'current'
          downloadType: 'specific'
          itemPattern: '**/*results.json'
          downloadPath: '$(Build.ArtifactStagingDirectory)'