trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage:
  jobs:
   - job:
     steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'Azure subscription 1(977812bc-0cfb-4c57-8912-a7804ccf8fba)'
         scriptType: 'bash'
         scriptLocation: 'inlineScript'
         inlineScript: './kube.sh'
         useGlobalConfig: true
         workingDirectory: $(System.DefaultWorkingDirectory)